version: '3.8'
services:
  qingpingtoinfluxdb:
    image: quantensittich/qingping2influxdb:latest
    restart: unless-stopped
    container_name: QingpingToInfluxDB
    environment:
      QINGPING_APPKEY: SAMPLE_APPKEY
      QINGPING_APPSECRET: SAMPLE_APPSECRET
      INFLUXDB_URL: http://user-influxdb-url
      INFLUXDB_TOKEN: user_token
      INFLUXDB_ORG: user_org
      INFLUXDB_BUCKET: user_bucket
      FETCH_INTERVAL: 20
      #DEBUG: "true" #uncomment if shall be enabled